/*
	STM32 example: log to a UART with a milliseconds-since-boot timestamp.

	This example relies on the code generated by STM32CubeMX (huart2 is
	initialized by MX_USART2_UART_Init()). Build with the STM32 family macro
	defined (for example -DSTM32F4) and compile these library files:
	  src/logging_core.c, src/backends/console.c, src/backends/file.c,
	  src/backends/serial_stm32.c, src/platforms/stm32.c

	With FreeRTOS the library creates its own mutex in log_platform_init().
	No application mutex or lock functions are needed.

	Output: [123456] INFO   [main] logging started
*/
#include "main.h"
#include <logging.h>

extern UART_HandleTypeDef huart2;

static log_backend_cfg_t log_backends[] = {
    {
        .type = LOG_OUTPUT_CUSTOM,
        .driver = &log_driver_serial_stm32,
        .level = LOGGING_LEVEL_DEBUG,
        .enabled = true,
        .config = &huart2,
        .timestamp_format = LOG_TS_ELAPSED_MS,
    },
};

/**
 * @brief Start logging
 *
 * Call from main() after MX_USART2_UART_Init() and before the scheduler
 * starts (osKernelStart() or vTaskStartScheduler()).
 */
void logging_setup(void) {
    log_platform_init();
    log_init(log_backends, sizeof(log_backends) / sizeof(log_backends[0]));
    LOGGING_INFO("main", "logging started");
}
