/*
	STM32 example: log to a UART with a timestamp read from the RTC.

	This example relies on the code generated by STM32CubeMX (hrtc and huart2
	are initialized by MX_RTC_Init() and MX_USART2_UART_Init()). Build with
	the STM32 family macro defined (for example -DSTM32F4) and compile these
	library files:
	  src/logging_core.c, src/backends/console.c, src/backends/file.c,
	  src/backends/serial_stm32.c, src/platforms/stm32.c

	The STM32 port has no wall clock, so the built-in date/time formats would
	print elapsed seconds. A custom timestamp formatter reads the RTC instead.

	Output: [14:05:09 09/26/26] INFO   [main] logging started
*/
#include <stdio.h>
#include "main.h"
#include "rtc.h"
#include <logging.h>

extern UART_HandleTypeDef huart2;

/**
 * @brief Timestamp formatter based on the RTC time and date
 *
 * Runs under the logging lock, once per backend and message.
 */
static int rtc_timestamp(uint64_t timestamp_us, char *buffer, size_t buffer_size) {
    RTC_TimeTypeDef tm;
    RTC_DateTypeDef dt;

    (void)timestamp_us;
    HAL_RTC_GetTime(&hrtc, &tm, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &dt, RTC_FORMAT_BIN);  // read the date after the time to unlock the shadow registers

    return snprintf(buffer, buffer_size, "%02u:%02u:%02u %02u/%02u/%02u",
                    tm.Hours, tm.Minutes, tm.Seconds, dt.Month, dt.Date, dt.Year);
}

static log_backend_cfg_t log_backends[] = {
    {
        .type = LOG_OUTPUT_CUSTOM,
        .driver = &log_driver_serial_stm32,
        .level = LOG_LEVEL_DEBUG,
        .enabled = true,
        .config = &huart2,
        .timestamp_format = LOG_TS_CUSTOM,
        .custom_ts_formatter = rtc_timestamp,
    },
};

/**
 * @brief Start logging
 *
 * Call from main() after MX_RTC_Init() and MX_USART2_UART_Init(), and before
 * the scheduler starts (osKernelStart() or vTaskStartScheduler()).
 */
void logging_setup(void) {
    log_platform_init();
    log_init(log_backends, sizeof(log_backends) / sizeof(log_backends[0]));
    LOG_INFO("main", "logging started");
}
